// ============================================================================
//
// Copyright (c) 2006-2015, Talend Inc.
//
// This source code has been automatically generated by_Talend Open Studio for Data Integration
// / Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package technip.test_0_1;

import routines.Numeric;
import routines.DataOperation;
import routines.TalendDataGenerator;
import routines.TalendStringUtil;
import routines.TalendString;
import routines.StringHandling;
import routines.Relational;
import routines.TalendDate;
import routines.Mathematical;
import routines.system.*;
import routines.system.api.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.math.BigDecimal;
import java.io.ByteArrayOutputStream;
import java.io.ByteArrayInputStream;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.ObjectOutputStream;
import java.io.ObjectInputStream;
import java.io.IOException;
import java.util.Comparator;

//the import part of tJava_4
//import java.util.List;

//the import part of tJava_6
//import java.util.List;

//the import part of tJava_7
//import java.util.List;

@SuppressWarnings("unused")
/**
 * Job: test Purpose: <br>
 * Description:  <br>
 * @author user@talend.com
 * @version 7.1.1.20181026_1147
 * @status 
 */
public class test implements TalendJob {

	protected static void logIgnoredError(String message, Throwable cause) {
		System.err.println(message);
		if (cause != null) {
			cause.printStackTrace();
		}

	}

	public final Object obj = new Object();

	// for transmiting parameters purpose
	private Object valueObject = null;

	public Object getValueObject() {
		return this.valueObject;
	}

	public void setValueObject(Object valueObject) {
		this.valueObject = valueObject;
	}

	private final static String defaultCharset = java.nio.charset.Charset
			.defaultCharset().name();

	private final static String utf8Charset = "UTF-8";

	// contains type for every context property
	public class PropertiesWithType extends java.util.Properties {
		private static final long serialVersionUID = 1L;
		private java.util.Map<String, String> propertyTypes = new java.util.HashMap<>();

		public PropertiesWithType(java.util.Properties properties) {
			super(properties);
		}

		public PropertiesWithType() {
			super();
		}

		public void setContextType(String key, String type) {
			propertyTypes.put(key, type);
		}

		public String getContextType(String key) {
			return propertyTypes.get(key);
		}
	}

	// create and load default properties
	private java.util.Properties defaultProps = new java.util.Properties();

	// create application properties with default
	public class ContextProperties extends PropertiesWithType {

		private static final long serialVersionUID = 1L;

		public ContextProperties(java.util.Properties properties) {
			super(properties);
		}

		public ContextProperties() {
			super();
		}

		public void synchronizeContext() {

			if (ID != null) {

				this.setProperty("ID", ID.toString());

			}

			if (FULL_Endpt != null) {

				this.setProperty("FULL_Endpt", FULL_Endpt.toString());

			}

			if (FULL_PassW != null) {

				this.setProperty("FULL_PassW", FULL_PassW.toString());

			}

			if (FULL_SecuK != null) {

				this.setProperty("FULL_SecuK", FULL_SecuK.toString());

			}

			if (FULL_UserId != null) {

				this.setProperty("FULL_UserId", FULL_UserId.toString());

			}

			if (CIBLE_Endpt != null) {

				this.setProperty("CIBLE_Endpt", CIBLE_Endpt.toString());

			}

			if (CIBLE_PassW != null) {

				this.setProperty("CIBLE_PassW", CIBLE_PassW.toString());

			}

			if (CIBLE_SecuK != null) {

				this.setProperty("CIBLE_SecuK", CIBLE_SecuK.toString());

			}

			if (CIBLE_UserId != null) {

				this.setProperty("CIBLE_UserId", CIBLE_UserId.toString());

			}

			if (SOURCE_Endpt != null) {

				this.setProperty("SOURCE_Endpt", SOURCE_Endpt.toString());

			}

			if (SOURCE_PassW != null) {

				this.setProperty("SOURCE_PassW", SOURCE_PassW.toString());

			}

			if (SOURCE_SecuK != null) {

				this.setProperty("SOURCE_SecuK", SOURCE_SecuK.toString());

			}

			if (SOURCE_UserId != null) {

				this.setProperty("SOURCE_UserId", SOURCE_UserId.toString());

			}

			if (offset != null) {

				this.setProperty("offset", offset.toString());

			}

			if (idcont != null) {

				this.setProperty("idcont", idcont.toString());

			}

			if (identif != null) {

				this.setProperty("identif", identif.toString());

			}

			if (somme != null) {

				this.setProperty("somme", somme.toString());

			}

		}

		public String ID;

		public String getID() {
			return this.ID;
		}

		public String FULL_Endpt;

		public String getFULL_Endpt() {
			return this.FULL_Endpt;
		}

		public java.lang.String FULL_PassW;

		public java.lang.String getFULL_PassW() {
			return this.FULL_PassW;
		}

		public java.lang.String FULL_SecuK;

		public java.lang.String getFULL_SecuK() {
			return this.FULL_SecuK;
		}

		public String FULL_UserId;

		public String getFULL_UserId() {
			return this.FULL_UserId;
		}

		public String CIBLE_Endpt;

		public String getCIBLE_Endpt() {
			return this.CIBLE_Endpt;
		}

		public java.lang.String CIBLE_PassW;

		public java.lang.String getCIBLE_PassW() {
			return this.CIBLE_PassW;
		}

		public java.lang.String CIBLE_SecuK;

		public java.lang.String getCIBLE_SecuK() {
			return this.CIBLE_SecuK;
		}

		public String CIBLE_UserId;

		public String getCIBLE_UserId() {
			return this.CIBLE_UserId;
		}

		public String SOURCE_Endpt;

		public String getSOURCE_Endpt() {
			return this.SOURCE_Endpt;
		}

		public java.lang.String SOURCE_PassW;

		public java.lang.String getSOURCE_PassW() {
			return this.SOURCE_PassW;
		}

		public java.lang.String SOURCE_SecuK;

		public java.lang.String getSOURCE_SecuK() {
			return this.SOURCE_SecuK;
		}

		public String SOURCE_UserId;

		public String getSOURCE_UserId() {
			return this.SOURCE_UserId;
		}

		public Integer offset;

		public Integer getOffset() {
			return this.offset;
		}

		public String idcont;

		public String getIdcont() {
			return this.idcont;
		}

		public Integer identif;

		public Integer getIdentif() {
			return this.identif;
		}

		public Integer somme;

		public Integer getSomme() {
			return this.somme;
		}
	}

	private ContextProperties context = new ContextProperties();

	public ContextProperties getContext() {
		return this.context;
	}

	private final String jobVersion = "0.1";
	private final String jobName = "test";
	private final String projectName = "TECHNIP";
	public Integer errorCode = null;
	private String currentComponent = "";

	private final java.util.Map<String, Object> globalMap = new java.util.HashMap<String, Object>();
	private final static java.util.Map<String, Object> junitGlobalMap = new java.util.HashMap<String, Object>();

	private final java.util.Map<String, Long> start_Hash = new java.util.HashMap<String, Long>();
	private final java.util.Map<String, Long> end_Hash = new java.util.HashMap<String, Long>();
	private final java.util.Map<String, Boolean> ok_Hash = new java.util.HashMap<String, Boolean>();
	public final java.util.List<String[]> globalBuffer = new java.util.ArrayList<String[]>();

	private RunStat runStat = new RunStat();

	// OSGi DataSource
	private final static String KEY_DB_DATASOURCES = "KEY_DB_DATASOURCES";

	private final static String KEY_DB_DATASOURCES_RAW = "KEY_DB_DATASOURCES_RAW";

	public void setDataSources(
			java.util.Map<String, javax.sql.DataSource> dataSources) {
		java.util.Map<String, routines.system.TalendDataSource> talendDataSources = new java.util.HashMap<String, routines.system.TalendDataSource>();
		for (java.util.Map.Entry<String, javax.sql.DataSource> dataSourceEntry : dataSources
				.entrySet()) {
			talendDataSources.put(
					dataSourceEntry.getKey(),
					new routines.system.TalendDataSource(dataSourceEntry
							.getValue()));
		}
		globalMap.put(KEY_DB_DATASOURCES, talendDataSources);
		globalMap
				.put(KEY_DB_DATASOURCES_RAW,
						new java.util.HashMap<String, javax.sql.DataSource>(
								dataSources));
	}

	private final java.io.ByteArrayOutputStream baos = new java.io.ByteArrayOutputStream();
	private final java.io.PrintStream errorMessagePS = new java.io.PrintStream(
			new java.io.BufferedOutputStream(baos));

	public String getExceptionStackTrace() {
		if ("failure".equals(this.getStatus())) {
			errorMessagePS.flush();
			return baos.toString();
		}
		return null;
	}

	private Exception exception;

	public Exception getException() {
		if ("failure".equals(this.getStatus())) {
			return this.exception;
		}
		return null;
	}

	private class TalendException extends Exception {

		private static final long serialVersionUID = 1L;

		private java.util.Map<String, Object> globalMap = null;
		private Exception e = null;
		private String currentComponent = null;
		private String virtualComponentName = null;

		public void setVirtualComponentName(String virtualComponentName) {
			this.virtualComponentName = virtualComponentName;
		}

		private TalendException(Exception e, String errorComponent,
				final java.util.Map<String, Object> globalMap) {
			this.currentComponent = errorComponent;
			this.globalMap = globalMap;
			this.e = e;
		}

		public Exception getException() {
			return this.e;
		}

		public String getCurrentComponent() {
			return this.currentComponent;
		}

		public String getExceptionCauseMessage(Exception e) {
			Throwable cause = e;
			String message = null;
			int i = 10;
			while (null != cause && 0 < i--) {
				message = cause.getMessage();
				if (null == message) {
					cause = cause.getCause();
				} else {
					break;
				}
			}
			if (null == message) {
				message = e.getClass().getName();
			}
			return message;
		}

		@Override
		public void printStackTrace() {
			if (!(e instanceof TalendException || e instanceof TDieException)) {
				if (virtualComponentName != null
						&& currentComponent.indexOf(virtualComponentName + "_") == 0) {
					globalMap.put(virtualComponentName + "_ERROR_MESSAGE",
							getExceptionCauseMessage(e));
				}
				globalMap.put(currentComponent + "_ERROR_MESSAGE",
						getExceptionCauseMessage(e));
				System.err.println("Exception in component " + currentComponent
						+ " (" + jobName + ")");
			}
			if (!(e instanceof TDieException)) {
				if (e instanceof TalendException) {
					e.printStackTrace();
				} else {
					e.printStackTrace();
					e.printStackTrace(errorMessagePS);
					test.this.exception = e;
				}
			}
			if (!(e instanceof TalendException)) {
				try {
					for (java.lang.reflect.Method m : this.getClass()
							.getEnclosingClass().getMethods()) {
						if (m.getName().compareTo(currentComponent + "_error") == 0) {
							m.invoke(test.this, new Object[] { e,
									currentComponent, globalMap });
							break;
						}
					}

					if (!(e instanceof TDieException)) {
					}
				} catch (Exception e) {
					this.e.printStackTrace();
				}
			}
		}
	}

	public void Implicit_Context_Regex_error(Exception exception,
			String errorComponent, final java.util.Map<String, Object> globalMap)
			throws TalendException {

		Implicit_Context_Context_error(exception, errorComponent, globalMap);

	}

	public void Implicit_Context_Context_error(Exception exception,
			String errorComponent, final java.util.Map<String, Object> globalMap)
			throws TalendException {

		end_Hash.put(errorComponent, System.currentTimeMillis());

		status = "failure";

		Implicit_Context_Regex_onSubJobError(exception, errorComponent,
				globalMap);
	}

	public void tFixedFlowInput_3_error(Exception exception,
			String errorComponent, final java.util.Map<String, Object> globalMap)
			throws TalendException {

		end_Hash.put(errorComponent, System.currentTimeMillis());

		status = "failure";

		tFixedFlowInput_3_onSubJobError(exception, errorComponent, globalMap);
	}

	public void tFlowToIterate_4_error(Exception exception,
			String errorComponent, final java.util.Map<String, Object> globalMap)
			throws TalendException {

		end_Hash.put(errorComponent, System.currentTimeMillis());

		status = "failure";

		tFixedFlowInput_3_onSubJobError(exception, errorComponent, globalMap);
	}

	public void tJava_4_error(Exception exception, String errorComponent,
			final java.util.Map<String, Object> globalMap)
			throws TalendException {

		end_Hash.put(errorComponent, System.currentTimeMillis());

		status = "failure";

		tFixedFlowInput_3_onSubJobError(exception, errorComponent, globalMap);
	}

	public void tJava_6_error(Exception exception, String errorComponent,
			final java.util.Map<String, Object> globalMap)
			throws TalendException {

		end_Hash.put(errorComponent, System.currentTimeMillis());

		status = "failure";

		tJava_6_onSubJobError(exception, errorComponent, globalMap);
	}

	public void tJava_7_error(Exception exception, String errorComponent,
			final java.util.Map<String, Object> globalMap)
			throws TalendException {

		end_Hash.put(errorComponent, System.currentTimeMillis());

		status = "failure";

		tJava_7_onSubJobError(exception, errorComponent, globalMap);
	}

	public void tRowGenerator_1_error(Exception exception,
			String errorComponent, final java.util.Map<String, Object> globalMap)
			throws TalendException {

		end_Hash.put(errorComponent, System.currentTimeMillis());

		status = "failure";

		tRowGenerator_1_onSubJobError(exception, errorComponent, globalMap);
	}

	public void tLogRow_5_error(Exception exception, String errorComponent,
			final java.util.Map<String, Object> globalMap)
			throws TalendException {

		end_Hash.put(errorComponent, System.currentTimeMillis());

		status = "failure";

		tRowGenerator_1_onSubJobError(exception, errorComponent, globalMap);
	}

	public void Implicit_Context_Regex_onSubJobError(Exception exception,
			String errorComponent, final java.util.Map<String, Object> globalMap)
			throws TalendException {

		resumeUtil.addLog("SYSTEM_LOG", "NODE:" + errorComponent, "", Thread
				.currentThread().getId() + "", "FATAL", "",
				exception.getMessage(),
				ResumeUtil.getExceptionStackTrace(exception), "");

	}

	public void tFixedFlowInput_3_onSubJobError(Exception exception,
			String errorComponent, final java.util.Map<String, Object> globalMap)
			throws TalendException {

		resumeUtil.addLog("SYSTEM_LOG", "NODE:" + errorComponent, "", Thread
				.currentThread().getId() + "", "FATAL", "",
				exception.getMessage(),
				ResumeUtil.getExceptionStackTrace(exception), "");

	}

	public void tJava_6_onSubJobError(Exception exception,
			String errorComponent, final java.util.Map<String, Object> globalMap)
			throws TalendException {

		resumeUtil.addLog("SYSTEM_LOG", "NODE:" + errorComponent, "", Thread
				.currentThread().getId() + "", "FATAL", "",
				exception.getMessage(),
				ResumeUtil.getExceptionStackTrace(exception), "");

	}

	public void tJava_7_onSubJobError(Exception exception,
			String errorComponent, final java.util.Map<String, Object> globalMap)
			throws TalendException {

		resumeUtil.addLog("SYSTEM_LOG", "NODE:" + errorComponent, "", Thread
				.currentThread().getId() + "", "FATAL", "",
				exception.getMessage(),
				ResumeUtil.getExceptionStackTrace(exception), "");

	}

	public void tRowGenerator_1_onSubJobError(Exception exception,
			String errorComponent, final java.util.Map<String, Object> globalMap)
			throws TalendException {

		resumeUtil.addLog("SYSTEM_LOG", "NODE:" + errorComponent, "", Thread
				.currentThread().getId() + "", "FATAL", "",
				exception.getMessage(),
				ResumeUtil.getExceptionStackTrace(exception), "");

	}

	public static class row_Implicit_Context_RegexStruct implements
			routines.system.IPersistableRow<row_Implicit_Context_RegexStruct> {
		final static byte[] commonByteArrayLock_TECHNIP_test = new byte[0];
		static byte[] commonByteArray_TECHNIP_test = new byte[0];

		public String key;

		public String getKey() {
			return this.key;
		}

		public String value;

		public String getValue() {
			return this.value;
		}

		private String readString(ObjectInputStream dis) throws IOException {
			String strReturn = null;
			int length = 0;
			length = dis.readInt();
			if (length == -1) {
				strReturn = null;
			} else {
				if (length > commonByteArray_TECHNIP_test.length) {
					if (length < 1024
							&& commonByteArray_TECHNIP_test.length == 0) {
						commonByteArray_TECHNIP_test = new byte[1024];
					} else {
						commonByteArray_TECHNIP_test = new byte[2 * length];
					}
				}
				dis.readFully(commonByteArray_TECHNIP_test, 0, length);
				strReturn = new String(commonByteArray_TECHNIP_test, 0, length,
						utf8Charset);
			}
			return strReturn;
		}

		private void writeString(String str, ObjectOutputStream dos)
				throws IOException {
			if (str == null) {
				dos.writeInt(-1);
			} else {
				byte[] byteArray = str.getBytes(utf8Charset);
				dos.writeInt(byteArray.length);
				dos.write(byteArray);
			}
		}

		public void readData(ObjectInputStream dis) {

			synchronized (commonByteArrayLock_TECHNIP_test) {

				try {

					int length = 0;

					this.key = readString(dis);

					this.value = readString(dis);

				} catch (IOException e) {
					throw new RuntimeException(e);

				}

			}

		}

		public void writeData(ObjectOutputStream dos) {
			try {

				// String

				writeString(this.key, dos);

				// String

				writeString(this.value, dos);

			} catch (IOException e) {
				throw new RuntimeException(e);
			}

		}

		public String toString() {

			StringBuilder sb = new StringBuilder();
			sb.append(super.toString());
			sb.append("[");
			sb.append("key=" + key);
			sb.append(",value=" + value);
			sb.append("]");

			return sb.toString();
		}

		/**
		 * Compare keys
		 */
		public int compareTo(row_Implicit_Context_RegexStruct other) {

			int returnValue = -1;

			return returnValue;
		}

		private int checkNullsAndCompare(Object object1, Object object2) {
			int returnValue = 0;
			if (object1 instanceof Comparable && object2 instanceof Comparable) {
				returnValue = ((Comparable) object1).compareTo(object2);
			} else if (object1 != null && object2 != null) {
				returnValue = compareStrings(object1.toString(),
						object2.toString());
			} else if (object1 == null && object2 != null) {
				returnValue = 1;
			} else if (object1 != null && object2 == null) {
				returnValue = -1;
			} else {
				returnValue = 0;
			}

			return returnValue;
		}

		private int compareStrings(String string1, String string2) {
			return string1.compareTo(string2);
		}

	}

	public void Implicit_Context_RegexProcess(
			final java.util.Map<String, Object> globalMap)
			throws TalendException {
		globalMap.put("Implicit_Context_Regex_SUBPROCESS_STATE", 0);

		final boolean execStat = this.execStat;
		String currentVirtualComponent = null;

		String iterateId = "";

		String currentComponent = "";
		java.util.Map<String, Object> resourceMap = new java.util.HashMap<String, Object>();

		try {
			// TDI-39566 avoid throwing an useless Exception
			boolean resumeIt = true;
			if (globalResumeTicket == false && resumeEntryMethodName != null) {
				String currentMethodName = new java.lang.Exception()
						.getStackTrace()[0].getMethodName();
				resumeIt = resumeEntryMethodName.equals(currentMethodName);
			}
			if (resumeIt || globalResumeTicket) { // start the resume
				globalResumeTicket = true;

				row_Implicit_Context_RegexStruct row_Implicit_Context_Regex = new row_Implicit_Context_RegexStruct();

				/**
				 * [Implicit_Context_Context begin ] start
				 */

				ok_Hash.put("Implicit_Context_Context", false);
				start_Hash.put("Implicit_Context_Context",
						System.currentTimeMillis());

				currentVirtualComponent = "Implicit_Context_Context";

				currentComponent = "Implicit_Context_Context";

				if (execStat) {
					if (resourceMap.get("inIterateVComp") == null) {

						runStat.updateStatOnConnection("Main" + iterateId, 0, 0);

					}
				}

				int tos_count_Implicit_Context_Context = 0;

				java.util.List<String> assignList_Implicit_Context_Context = new java.util.ArrayList<String>();
				java.util.List<String> newPropertyList_Implicit_Context_Context = new java.util.ArrayList<String>();
				java.util.List<String> noAssignList_Implicit_Context_Context = new java.util.ArrayList<String>();
				int nb_line_Implicit_Context_Context = 0;

				/**
				 * [Implicit_Context_Context begin ] stop
				 */

				/**
				 * [Implicit_Context_Regex begin ] start
				 */

				ok_Hash.put("Implicit_Context_Regex", false);
				start_Hash.put("Implicit_Context_Regex",
						System.currentTimeMillis());

				currentVirtualComponent = "Implicit_Context_Regex";

				currentComponent = "Implicit_Context_Regex";

				int tos_count_Implicit_Context_Regex = 0;

				int nb_line_Implicit_Context_Regex = 0;

				int footer_Implicit_Context_Regex = 0;
				boolean removeEmptyRowImplicit_Context_Regex = true;
				Object source_Implicit_Context_Regex = /**
				 * Start field
				 * Implicit_Context_Regex:FILENAME
				 */
				"C:/Users/Cillia/Desktop/TalendWork/Commun/config.properties"/**
				 * 
				 * End field Implicit_Context_Regex:FILENAME
				 */
				;

				org.talend.fileprocess.TOSDelimitedReader inImplicit_Context_Regex = null;
				if (source_Implicit_Context_Regex instanceof String
						|| source_Implicit_Context_Regex instanceof java.io.InputStream) {
					inImplicit_Context_Regex = new org.talend.fileprocess.TOSDelimitedReader(/**
					 * 
					 * Start field Implicit_Context_Regex:FILENAME
					 */
					"C:/Users/Cillia/Desktop/TalendWork/Commun/config.properties"/**
					 * 
					 * End field Implicit_Context_Regex:FILENAME
					 */
					, "ISO-8859-15", "", "\n",
							removeEmptyRowImplicit_Context_Regex);
				} else {
					throw new java.lang.Exception(
							"The source data should be specified as File Path or InputStream or java.io.Reader!");
				}
				String strImplicit_Context_Regex;
				int totalLineImplicit_Context_Regex = 0, currentLineImplicit_Context_Regex = 0, beginLineImplicit_Context_Regex = 0, lastLineImplicit_Context_Regex = -1, validRowCountImplicit_Context_Regex = 0;
				int limitImplicit_Context_Regex = -1;

				int headerImplicit_Context_Regex = 0;
				if (headerImplicit_Context_Regex > 0) {
					beginLineImplicit_Context_Regex = headerImplicit_Context_Regex + 1;
				}

				if (footer_Implicit_Context_Regex > 0) {
					while (inImplicit_Context_Regex.readRecord()) {
						strImplicit_Context_Regex = inImplicit_Context_Regex
								.getRowRecord();
						totalLineImplicit_Context_Regex++;
					}
					int lastLineTempImplicit_Context_Regex = totalLineImplicit_Context_Regex
							- footer_Implicit_Context_Regex < 0 ? 0
							: totalLineImplicit_Context_Regex
									- footer_Implicit_Context_Regex;
					if (lastLineImplicit_Context_Regex > 0) {
						lastLineImplicit_Context_Regex = lastLineImplicit_Context_Regex < lastLineTempImplicit_Context_Regex ? lastLineImplicit_Context_Regex
								: lastLineTempImplicit_Context_Regex;
					} else {
						lastLineImplicit_Context_Regex = lastLineTempImplicit_Context_Regex;
					}
					inImplicit_Context_Regex.close();
					inImplicit_Context_Regex = new org.talend.fileprocess.TOSDelimitedReader(/**
					 * 
					 * Start field Implicit_Context_Regex:FILENAME
					 */
					"C:/Users/Cillia/Desktop/TalendWork/Commun/config.properties"/**
					 * 
					 * End field Implicit_Context_Regex:FILENAME
					 */
					, "ISO-8859-15", "", "\n",
							removeEmptyRowImplicit_Context_Regex);
				}
				java.util.StringTokenizer strTokenImplicit_Context_Regex;
				java.util.regex.Pattern patternImplicit_Context_Regex = java.util.regex.Pattern
						.compile("^([^" + "==" + "]*)" + "==" + "(.*)$");
				java.util.regex.Matcher matcherImplicit_Context_Regex = null;

				while (inImplicit_Context_Regex.readRecord()) {
					strImplicit_Context_Regex = inImplicit_Context_Regex
							.getRowRecord();

					currentLineImplicit_Context_Regex++;
					if (currentLineImplicit_Context_Regex < beginLineImplicit_Context_Regex) {
						continue;
					}
					if (lastLineImplicit_Context_Regex > -1
							&& currentLineImplicit_Context_Regex > lastLineImplicit_Context_Regex) {
						break;
					}
					if (removeEmptyRowImplicit_Context_Regex
							&& ("").equals(strImplicit_Context_Regex)) {
						continue;
					}
					if (limitImplicit_Context_Regex != -1
							&& validRowCountImplicit_Context_Regex >= limitImplicit_Context_Regex) {
						break;
					}

					matcherImplicit_Context_Regex = patternImplicit_Context_Regex
							.matcher(strImplicit_Context_Regex);
					int groupCountImplicit_Context_Regex = 0;
					boolean isMatchImplicit_Context_Regex = matcherImplicit_Context_Regex
							.find();
					if (isMatchImplicit_Context_Regex) {
						groupCountImplicit_Context_Regex = matcherImplicit_Context_Regex
								.groupCount();
					}
					row_Implicit_Context_Regex = null;

					boolean lineIsEmptyImplicit_Context_Regex = strImplicit_Context_Regex
							.length() == 0;

					String[] valueImplicit_Context_Regex = new String[2];
					String frontCharImplicit_Context_Regex, behindCharImplicit_Context_Regex;
					for (int i = 0; i < 2; i++) {
						valueImplicit_Context_Regex[i] = "";
						if (lineIsEmptyImplicit_Context_Regex) {
							continue;
						}
						if (i < groupCountImplicit_Context_Regex) {
							valueImplicit_Context_Regex[i] = matcherImplicit_Context_Regex
									.group(i + 1);
						}
					}
					validRowCountImplicit_Context_Regex++;

					boolean whetherReject_Implicit_Context_Regex = false;
					row_Implicit_Context_Regex = new row_Implicit_Context_RegexStruct();
					try {
						if (!isMatchImplicit_Context_Regex) {// line data not
																// matched with
																// given regex
																// parameter
							throw new java.lang.Exception(
									"Line doesn't match: "
											+ strImplicit_Context_Regex);
						}

						if (valueImplicit_Context_Regex[0] != null
								&& valueImplicit_Context_Regex[0].length() > 0) {
							row_Implicit_Context_Regex.key = valueImplicit_Context_Regex[0];
						} else {
							row_Implicit_Context_Regex.key = "";
						}

						if (valueImplicit_Context_Regex[1] != null
								&& valueImplicit_Context_Regex[1].length() > 0) {
							row_Implicit_Context_Regex.value = valueImplicit_Context_Regex[1];
						} else {
							row_Implicit_Context_Regex.value = "";
						}

					} catch (java.lang.Exception e) {
						whetherReject_Implicit_Context_Regex = true;
						if (isMatchImplicit_Context_Regex) {
							System.err.println(e.getMessage());
						}
						row_Implicit_Context_Regex = null;
					}

					nb_line_Implicit_Context_Regex++;

					/**
					 * [Implicit_Context_Regex begin ] stop
					 */

					/**
					 * [Implicit_Context_Regex main ] start
					 */

					currentVirtualComponent = "Implicit_Context_Regex";

					currentComponent = "Implicit_Context_Regex";

					tos_count_Implicit_Context_Regex++;

					/**
					 * [Implicit_Context_Regex main ] stop
					 */

					/**
					 * [Implicit_Context_Regex process_data_begin ] start
					 */

					currentVirtualComponent = "Implicit_Context_Regex";

					currentComponent = "Implicit_Context_Regex";

					/**
					 * [Implicit_Context_Regex process_data_begin ] stop
					 */
					// Start of branch "row_Implicit_Context_Regex"
					if (row_Implicit_Context_Regex != null) {

						/**
						 * [Implicit_Context_Context main ] start
						 */

						currentVirtualComponent = "Implicit_Context_Context";

						currentComponent = "Implicit_Context_Context";

						// Main
						// row_Implicit_Context_Regex

						if (execStat) {
							runStat.updateStatOnConnection("Main" + iterateId,
									1, 1);
						}

						// ////////////////////////
						String tmp_key_Implicit_Context_Context = null;
						String key_Implicit_Context_Context = null;
						if (row_Implicit_Context_Regex.key != null) {
							tmp_key_Implicit_Context_Context = row_Implicit_Context_Regex.key
									.trim();
							if ((tmp_key_Implicit_Context_Context
									.startsWith("#") || tmp_key_Implicit_Context_Context
									.startsWith("!"))) {
								tmp_key_Implicit_Context_Context = null;
							} else {
								row_Implicit_Context_Regex.key = tmp_key_Implicit_Context_Context;
							}
						}
						if (row_Implicit_Context_Regex.key != null) {
							key_Implicit_Context_Context = row_Implicit_Context_Regex.key;
						}
						String value_Implicit_Context_Context = null;
						if (row_Implicit_Context_Regex.value != null) {
							value_Implicit_Context_Context = row_Implicit_Context_Regex.value;
						}

						String currentValue_Implicit_Context_Context = value_Implicit_Context_Context;

						if ((key_Implicit_Context_Context != null)
								&& ("FULL_PassW"
										.equals(key_Implicit_Context_Context)))
							currentValue_Implicit_Context_Context = currentValue_Implicit_Context_Context
									.replaceAll(".", "*");
						if ((key_Implicit_Context_Context != null)
								&& ("FULL_SecuK"
										.equals(key_Implicit_Context_Context)))
							currentValue_Implicit_Context_Context = currentValue_Implicit_Context_Context
									.replaceAll(".", "*");
						if ((key_Implicit_Context_Context != null)
								&& ("CIBLE_PassW"
										.equals(key_Implicit_Context_Context)))
							currentValue_Implicit_Context_Context = currentValue_Implicit_Context_Context
									.replaceAll(".", "*");
						if ((key_Implicit_Context_Context != null)
								&& ("CIBLE_SecuK"
										.equals(key_Implicit_Context_Context)))
							currentValue_Implicit_Context_Context = currentValue_Implicit_Context_Context
									.replaceAll(".", "*");
						if ((key_Implicit_Context_Context != null)
								&& ("SOURCE_PassW"
										.equals(key_Implicit_Context_Context)))
							currentValue_Implicit_Context_Context = currentValue_Implicit_Context_Context
									.replaceAll(".", "*");
						if ((key_Implicit_Context_Context != null)
								&& ("SOURCE_SecuK"
										.equals(key_Implicit_Context_Context)))
							currentValue_Implicit_Context_Context = currentValue_Implicit_Context_Context
									.replaceAll(".", "*");

						if (tmp_key_Implicit_Context_Context != null) {
							try {
								if (key_Implicit_Context_Context != null
										&& "ID".equals(key_Implicit_Context_Context)) {
									context.ID = value_Implicit_Context_Context;
								}

								if (key_Implicit_Context_Context != null
										&& "FULL_Endpt"
												.equals(key_Implicit_Context_Context)) {
									context.FULL_Endpt = value_Implicit_Context_Context;
								}

								if (key_Implicit_Context_Context != null
										&& "FULL_PassW"
												.equals(key_Implicit_Context_Context)) {
									context.FULL_PassW = value_Implicit_Context_Context;
								}

								if (key_Implicit_Context_Context != null
										&& "FULL_SecuK"
												.equals(key_Implicit_Context_Context)) {
									context.FULL_SecuK = value_Implicit_Context_Context;
								}

								if (key_Implicit_Context_Context != null
										&& "FULL_UserId"
												.equals(key_Implicit_Context_Context)) {
									context.FULL_UserId = value_Implicit_Context_Context;
								}

								if (key_Implicit_Context_Context != null
										&& "CIBLE_Endpt"
												.equals(key_Implicit_Context_Context)) {
									context.CIBLE_Endpt = value_Implicit_Context_Context;
								}

								if (key_Implicit_Context_Context != null
										&& "CIBLE_PassW"
												.equals(key_Implicit_Context_Context)) {
									context.CIBLE_PassW = value_Implicit_Context_Context;
								}

								if (key_Implicit_Context_Context != null
										&& "CIBLE_SecuK"
												.equals(key_Implicit_Context_Context)) {
									context.CIBLE_SecuK = value_Implicit_Context_Context;
								}

								if (key_Implicit_Context_Context != null
										&& "CIBLE_UserId"
												.equals(key_Implicit_Context_Context)) {
									context.CIBLE_UserId = value_Implicit_Context_Context;
								}

								if (key_Implicit_Context_Context != null
										&& "SOURCE_Endpt"
												.equals(key_Implicit_Context_Context)) {
									context.SOURCE_Endpt = value_Implicit_Context_Context;
								}

								if (key_Implicit_Context_Context != null
										&& "SOURCE_PassW"
												.equals(key_Implicit_Context_Context)) {
									context.SOURCE_PassW = value_Implicit_Context_Context;
								}

								if (key_Implicit_Context_Context != null
										&& "SOURCE_SecuK"
												.equals(key_Implicit_Context_Context)) {
									context.SOURCE_SecuK = value_Implicit_Context_Context;
								}

								if (key_Implicit_Context_Context != null
										&& "SOURCE_UserId"
												.equals(key_Implicit_Context_Context)) {
									context.SOURCE_UserId = value_Implicit_Context_Context;
								}

								if (key_Implicit_Context_Context != null
										&& "offset"
												.equals(key_Implicit_Context_Context)) {

									context.offset = Integer
											.parseInt(value_Implicit_Context_Context);

								}

								if (key_Implicit_Context_Context != null
										&& "idcont"
												.equals(key_Implicit_Context_Context)) {
									context.idcont = value_Implicit_Context_Context;
								}

								if (key_Implicit_Context_Context != null
										&& "identif"
												.equals(key_Implicit_Context_Context)) {

									context.identif = Integer
											.parseInt(value_Implicit_Context_Context);

								}

								if (key_Implicit_Context_Context != null
										&& "somme"
												.equals(key_Implicit_Context_Context)) {

									context.somme = Integer
											.parseInt(value_Implicit_Context_Context);

								}

								if (context
										.getProperty(key_Implicit_Context_Context) != null) {
									assignList_Implicit_Context_Context
											.add(key_Implicit_Context_Context);
								} else {
									newPropertyList_Implicit_Context_Context
											.add(key_Implicit_Context_Context);
								}
								if (value_Implicit_Context_Context == null) {
									context.setProperty(
											key_Implicit_Context_Context, "");
								} else {
									context.setProperty(
											key_Implicit_Context_Context,
											value_Implicit_Context_Context);
								}
							} catch (java.lang.Exception e) {
								System.err
										.println("Setting a value for the key \""
												+ key_Implicit_Context_Context
												+ "\" has failed. Error message: "
												+ e.getMessage());
							}
							nb_line_Implicit_Context_Context++;
						}
						// ////////////////////////

						tos_count_Implicit_Context_Context++;

						/**
						 * [Implicit_Context_Context main ] stop
						 */

						/**
						 * [Implicit_Context_Context process_data_begin ] start
						 */

						currentVirtualComponent = "Implicit_Context_Context";

						currentComponent = "Implicit_Context_Context";

						/**
						 * [Implicit_Context_Context process_data_begin ] stop
						 */

						/**
						 * [Implicit_Context_Context process_data_end ] start
						 */

						currentVirtualComponent = "Implicit_Context_Context";

						currentComponent = "Implicit_Context_Context";

						/**
						 * [Implicit_Context_Context process_data_end ] stop
						 */

					} // End of branch "row_Implicit_Context_Regex"

					/**
					 * [Implicit_Context_Regex process_data_end ] start
					 */

					currentVirtualComponent = "Implicit_Context_Regex";

					currentComponent = "Implicit_Context_Regex";

					/**
					 * [Implicit_Context_Regex process_data_end ] stop
					 */

					/**
					 * [Implicit_Context_Regex end ] start
					 */

					currentVirtualComponent = "Implicit_Context_Regex";

					currentComponent = "Implicit_Context_Regex";

				}
				if (!(source_Implicit_Context_Regex instanceof java.io.InputStream)) {
					inImplicit_Context_Regex.close();
				}
				inImplicit_Context_Regex = null;
				globalMap.put("Implicit_Context_Regex_NB_LINE",
						nb_line_Implicit_Context_Regex);

				ok_Hash.put("Implicit_Context_Regex", true);
				end_Hash.put("Implicit_Context_Regex",
						System.currentTimeMillis());

				/**
				 * [Implicit_Context_Regex end ] stop
				 */

				/**
				 * [Implicit_Context_Context end ] start
				 */

				currentVirtualComponent = "Implicit_Context_Context";

				currentComponent = "Implicit_Context_Context";

				java.util.Enumeration<?> enu_Implicit_Context_Context = context
						.propertyNames();
				while (enu_Implicit_Context_Context.hasMoreElements()) {
					String key_Implicit_Context_Context = (String) enu_Implicit_Context_Context
							.nextElement();
					if (!assignList_Implicit_Context_Context
							.contains(key_Implicit_Context_Context)
							&& !newPropertyList_Implicit_Context_Context
									.contains(key_Implicit_Context_Context)) {
						noAssignList_Implicit_Context_Context
								.add(key_Implicit_Context_Context);
					}
				}

				String newPropertyStr_Implicit_Context_Context = newPropertyList_Implicit_Context_Context
						.toString();
				String newProperty_Implicit_Context_Context = newPropertyStr_Implicit_Context_Context
						.substring(1, newPropertyStr_Implicit_Context_Context
								.length() - 1);

				String noAssignStr_Implicit_Context_Context = noAssignList_Implicit_Context_Context
						.toString();
				String noAssign_Implicit_Context_Context = noAssignStr_Implicit_Context_Context
						.substring(
								1,
								noAssignStr_Implicit_Context_Context.length() - 1);

				globalMap.put("Implicit_Context_Context_KEY_NOT_INCONTEXT",
						newProperty_Implicit_Context_Context);
				globalMap.put("Implicit_Context_Context_KEY_NOT_LOADED",
						noAssign_Implicit_Context_Context);

				globalMap.put("Implicit_Context_Context_NB_LINE",
						nb_line_Implicit_Context_Context);

				List<String> parametersToEncrypt_Implicit_Context_Context = new java.util.ArrayList<String>();

				parametersToEncrypt_Implicit_Context_Context.add("FULL_PassW");

				parametersToEncrypt_Implicit_Context_Context.add("FULL_SecuK");

				parametersToEncrypt_Implicit_Context_Context.add("CIBLE_PassW");

				parametersToEncrypt_Implicit_Context_Context.add("CIBLE_SecuK");

				parametersToEncrypt_Implicit_Context_Context
						.add("SOURCE_PassW");

				parametersToEncrypt_Implicit_Context_Context
						.add("SOURCE_SecuK");

				resumeUtil.addLog("NODE", "NODE:Implicit_Context_Context", "",
						Thread.currentThread().getId() + "", "", "", "", "",
						resumeUtil.convertToJsonText(context,
								parametersToEncrypt_Implicit_Context_Context));

				if (execStat) {
					if (resourceMap.get("inIterateVComp") == null
							|| !((Boolean) resourceMap.get("inIterateVComp"))) {
						runStat.updateStatOnConnection("Main" + iterateId, 2, 0);
					}
				}

				ok_Hash.put("Implicit_Context_Context", true);
				end_Hash.put("Implicit_Context_Context",
						System.currentTimeMillis());

				/**
				 * [Implicit_Context_Context end ] stop
				 */

			}// end the resume

		} catch (java.lang.Exception e) {

			TalendException te = new TalendException(e, currentComponent,
					globalMap);

			te.setVirtualComponentName(currentVirtualComponent);

			throw te;
		} catch (java.lang.Error error) {

			runStat.stopThreadStat();

			throw error;
		} finally {

			try {

				/**
				 * [Implicit_Context_Regex finally ] start
				 */

				currentVirtualComponent = "Implicit_Context_Regex";

				currentComponent = "Implicit_Context_Regex";

				/**
				 * [Implicit_Context_Regex finally ] stop
				 */

				/**
				 * [Implicit_Context_Context finally ] start
				 */

				currentVirtualComponent = "Implicit_Context_Context";

				currentComponent = "Implicit_Context_Context";

				/**
				 * [Implicit_Context_Context finally ] stop
				 */

			} catch (java.lang.Exception e) {
				// ignore
			} catch (java.lang.Error error) {
				// ignore
			}
			resourceMap = null;
		}

		globalMap.put("Implicit_Context_Regex_SUBPROCESS_STATE", 1);
	}

	public static class row15Struct implements
			routines.system.IPersistableRow<row15Struct> {
		final static byte[] commonByteArrayLock_TECHNIP_test = new byte[0];
		static byte[] commonByteArray_TECHNIP_test = new byte[0];

		public Integer identif;

		public Integer getIdentif() {
			return this.identif;
		}

		private Integer readInteger(ObjectInputStream dis) throws IOException {
			Integer intReturn;
			int length = 0;
			length = dis.readByte();
			if (length == -1) {
				intReturn = null;
			} else {
				intReturn = dis.readInt();
			}
			return intReturn;
		}

		private void writeInteger(Integer intNum, ObjectOutputStream dos)
				throws IOException {
			if (intNum == null) {
				dos.writeByte(-1);
			} else {
				dos.writeByte(0);
				dos.writeInt(intNum);
			}
		}

		public void readData(ObjectInputStream dis) {

			synchronized (commonByteArrayLock_TECHNIP_test) {

				try {

					int length = 0;

					this.identif = readInteger(dis);

				} catch (IOException e) {
					throw new RuntimeException(e);

				}

			}

		}

		public void writeData(ObjectOutputStream dos) {
			try {

				// Integer

				writeInteger(this.identif, dos);

			} catch (IOException e) {
				throw new RuntimeException(e);
			}

		}

		public String toString() {

			StringBuilder sb = new StringBuilder();
			sb.append(super.toString());
			sb.append("[");
			sb.append("identif=" + String.valueOf(identif));
			sb.append("]");

			return sb.toString();
		}

		/**
		 * Compare keys
		 */
		public int compareTo(row15Struct other) {

			int returnValue = -1;

			return returnValue;
		}

		private int checkNullsAndCompare(Object object1, Object object2) {
			int returnValue = 0;
			if (object1 instanceof Comparable && object2 instanceof Comparable) {
				returnValue = ((Comparable) object1).compareTo(object2);
			} else if (object1 != null && object2 != null) {
				returnValue = compareStrings(object1.toString(),
						object2.toString());
			} else if (object1 == null && object2 != null) {
				returnValue = 1;
			} else if (object1 != null && object2 == null) {
				returnValue = -1;
			} else {
				returnValue = 0;
			}

			return returnValue;
		}

		private int compareStrings(String string1, String string2) {
			return string1.compareTo(string2);
		}

	}

	public void tFixedFlowInput_3Process(
			final java.util.Map<String, Object> globalMap)
			throws TalendException {
		globalMap.put("tFixedFlowInput_3_SUBPROCESS_STATE", 0);

		final boolean execStat = this.execStat;

		String iterateId = "";

		String currentComponent = "";
		java.util.Map<String, Object> resourceMap = new java.util.HashMap<String, Object>();

		try {
			// TDI-39566 avoid throwing an useless Exception
			boolean resumeIt = true;
			if (globalResumeTicket == false && resumeEntryMethodName != null) {
				String currentMethodName = new java.lang.Exception()
						.getStackTrace()[0].getMethodName();
				resumeIt = resumeEntryMethodName.equals(currentMethodName);
			}
			if (resumeIt || globalResumeTicket) { // start the resume
				globalResumeTicket = true;

				row15Struct row15 = new row15Struct();

				/**
				 * [tFlowToIterate_4 begin ] start
				 */

				int NB_ITERATE_tJava_4 = 0; // for statistics

				ok_Hash.put("tFlowToIterate_4", false);
				start_Hash.put("tFlowToIterate_4", System.currentTimeMillis());

				currentComponent = "tFlowToIterate_4";

				if (execStat) {
					if (resourceMap.get("inIterateVComp") == null) {

						runStat.updateStatOnConnection("row15" + iterateId, 0,
								0);

					}
				}

				int tos_count_tFlowToIterate_4 = 0;

				int nb_line_tFlowToIterate_4 = 0;
				int counter_tFlowToIterate_4 = 0;

				/**
				 * [tFlowToIterate_4 begin ] stop
				 */

				/**
				 * [tFixedFlowInput_3 begin ] start
				 */

				ok_Hash.put("tFixedFlowInput_3", false);
				start_Hash.put("tFixedFlowInput_3", System.currentTimeMillis());

				currentComponent = "tFixedFlowInput_3";

				int tos_count_tFixedFlowInput_3 = 0;

				int nb_line_tFixedFlowInput_3 = 0;
				List<row15Struct> cacheList_tFixedFlowInput_3 = new java.util.ArrayList<row15Struct>();
				row15 = new row15Struct();
				row15.identif = 15;
				cacheList_tFixedFlowInput_3.add(row15);
				row15 = new row15Struct();
				row15.identif = 87;
				cacheList_tFixedFlowInput_3.add(row15);
				row15 = new row15Struct();
				row15.identif = 1;
				cacheList_tFixedFlowInput_3.add(row15);
				row15 = new row15Struct();
				row15.identif = 20;
				cacheList_tFixedFlowInput_3.add(row15);
				for (int i_tFixedFlowInput_3 = 0; i_tFixedFlowInput_3 < 1; i_tFixedFlowInput_3++) {
					for (row15Struct tmpRow_tFixedFlowInput_3 : cacheList_tFixedFlowInput_3) {
						nb_line_tFixedFlowInput_3++;
						row15 = tmpRow_tFixedFlowInput_3;

						/**
						 * [tFixedFlowInput_3 begin ] stop
						 */

						/**
						 * [tFixedFlowInput_3 main ] start
						 */

						currentComponent = "tFixedFlowInput_3";

						tos_count_tFixedFlowInput_3++;

						/**
						 * [tFixedFlowInput_3 main ] stop
						 */

						/**
						 * [tFixedFlowInput_3 process_data_begin ] start
						 */

						currentComponent = "tFixedFlowInput_3";

						/**
						 * [tFixedFlowInput_3 process_data_begin ] stop
						 */

						/**
						 * [tFlowToIterate_4 main ] start
						 */

						currentComponent = "tFlowToIterate_4";

						// row15
						// row15

						if (execStat) {
							runStat.updateStatOnConnection("row15" + iterateId,
									1, 1);
						}

						globalMap.put("row15.identif", row15.identif);

						nb_line_tFlowToIterate_4++;
						counter_tFlowToIterate_4++;
						globalMap.put("tFlowToIterate_4_CURRENT_ITERATION",
								counter_tFlowToIterate_4);

						tos_count_tFlowToIterate_4++;

						/**
						 * [tFlowToIterate_4 main ] stop
						 */

						/**
						 * [tFlowToIterate_4 process_data_begin ] start
						 */

						currentComponent = "tFlowToIterate_4";

						/**
						 * [tFlowToIterate_4 process_data_begin ] stop
						 */
						NB_ITERATE_tJava_4++;

						if (execStat) {
							runStat.updateStatOnConnection("OnSubjobOk5", 3, 0);
						}

						if (execStat) {
							runStat.updateStatOnConnection("OnComponentOk5", 3,
									0);
						}

						if (execStat) {
							runStat.updateStatOnConnection("iterate5", 1,
									"exec" + NB_ITERATE_tJava_4);
							// Thread.sleep(1000);
						}

						/**
						 * [tJava_4 begin ] start
						 */

						ok_Hash.put("tJava_4", false);
						start_Hash.put("tJava_4", System.currentTimeMillis());

						currentComponent = "tJava_4";

						int tos_count_tJava_4 = 0;

						String foo = "bar";
						context.identif = (Integer) globalMap
								.get("row15.identif");

						/**
						 * [tJava_4 begin ] stop
						 */

						/**
						 * [tJava_4 main ] start
						 */

						currentComponent = "tJava_4";

						tos_count_tJava_4++;

						/**
						 * [tJava_4 main ] stop
						 */

						/**
						 * [tJava_4 process_data_begin ] start
						 */

						currentComponent = "tJava_4";

						/**
						 * [tJava_4 process_data_begin ] stop
						 */

						/**
						 * [tJava_4 process_data_end ] start
						 */

						currentComponent = "tJava_4";

						/**
						 * [tJava_4 process_data_end ] stop
						 */

						/**
						 * [tJava_4 end ] start
						 */

						currentComponent = "tJava_4";

						ok_Hash.put("tJava_4", true);
						end_Hash.put("tJava_4", System.currentTimeMillis());

						if (execStat) {
							runStat.updateStatOnConnection("OnComponentOk5", 0,
									"ok");
						}
						tJava_6Process(globalMap);

						/**
						 * [tJava_4 end ] stop
						 */
						if (execStat) {
							runStat.updateStatOnConnection("iterate5", 2,
									"exec" + NB_ITERATE_tJava_4);
						}

						/**
						 * [tFlowToIterate_4 process_data_end ] start
						 */

						currentComponent = "tFlowToIterate_4";

						/**
						 * [tFlowToIterate_4 process_data_end ] stop
						 */

						/**
						 * [tFixedFlowInput_3 process_data_end ] start
						 */

						currentComponent = "tFixedFlowInput_3";

						/**
						 * [tFixedFlowInput_3 process_data_end ] stop
						 */

						/**
						 * [tFixedFlowInput_3 end ] start
						 */

						currentComponent = "tFixedFlowInput_3";

					}
				}
				cacheList_tFixedFlowInput_3.clear();
				globalMap.put("tFixedFlowInput_3_NB_LINE",
						nb_line_tFixedFlowInput_3);

				ok_Hash.put("tFixedFlowInput_3", true);
				end_Hash.put("tFixedFlowInput_3", System.currentTimeMillis());

				/**
				 * [tFixedFlowInput_3 end ] stop
				 */

				/**
				 * [tFlowToIterate_4 end ] start
				 */

				currentComponent = "tFlowToIterate_4";

				globalMap.put("tFlowToIterate_4_NB_LINE",
						nb_line_tFlowToIterate_4);
				if (execStat) {
					if (resourceMap.get("inIterateVComp") == null
							|| !((Boolean) resourceMap.get("inIterateVComp"))) {
						runStat.updateStatOnConnection("row15" + iterateId, 2,
								0);
					}
				}

				ok_Hash.put("tFlowToIterate_4", true);
				end_Hash.put("tFlowToIterate_4", System.currentTimeMillis());

				/**
				 * [tFlowToIterate_4 end ] stop
				 */

			}// end the resume

		} catch (java.lang.Exception e) {

			TalendException te = new TalendException(e, currentComponent,
					globalMap);

			throw te;
		} catch (java.lang.Error error) {

			runStat.stopThreadStat();

			throw error;
		} finally {

			try {

				/**
				 * [tFixedFlowInput_3 finally ] start
				 */

				currentComponent = "tFixedFlowInput_3";

				/**
				 * [tFixedFlowInput_3 finally ] stop
				 */

				/**
				 * [tFlowToIterate_4 finally ] start
				 */

				currentComponent = "tFlowToIterate_4";

				/**
				 * [tFlowToIterate_4 finally ] stop
				 */

				/**
				 * [tJava_4 finally ] start
				 */

				currentComponent = "tJava_4";

				/**
				 * [tJava_4 finally ] stop
				 */

			} catch (java.lang.Exception e) {
				// ignore
			} catch (java.lang.Error error) {
				// ignore
			}
			resourceMap = null;
		}

		globalMap.put("tFixedFlowInput_3_SUBPROCESS_STATE", 1);
	}

	public void tJava_6Process(final java.util.Map<String, Object> globalMap)
			throws TalendException {
		globalMap.put("tJava_6_SUBPROCESS_STATE", 0);

		final boolean execStat = this.execStat;

		String iterateId = "";

		String currentComponent = "";
		java.util.Map<String, Object> resourceMap = new java.util.HashMap<String, Object>();

		try {
			// TDI-39566 avoid throwing an useless Exception
			boolean resumeIt = true;
			if (globalResumeTicket == false && resumeEntryMethodName != null) {
				String currentMethodName = new java.lang.Exception()
						.getStackTrace()[0].getMethodName();
				resumeIt = resumeEntryMethodName.equals(currentMethodName);
			}
			if (resumeIt || globalResumeTicket) { // start the resume
				globalResumeTicket = true;

				/**
				 * [tJava_6 begin ] start
				 */

				ok_Hash.put("tJava_6", false);
				start_Hash.put("tJava_6", System.currentTimeMillis());

				currentComponent = "tJava_6";

				int tos_count_tJava_6 = 0;

				String foo = "bar";
				System.out.println(context.identif);

				/**
				 * [tJava_6 begin ] stop
				 */

				/**
				 * [tJava_6 main ] start
				 */

				currentComponent = "tJava_6";

				tos_count_tJava_6++;

				/**
				 * [tJava_6 main ] stop
				 */

				/**
				 * [tJava_6 process_data_begin ] start
				 */

				currentComponent = "tJava_6";

				/**
				 * [tJava_6 process_data_begin ] stop
				 */

				/**
				 * [tJava_6 process_data_end ] start
				 */

				currentComponent = "tJava_6";

				/**
				 * [tJava_6 process_data_end ] stop
				 */

				/**
				 * [tJava_6 end ] start
				 */

				currentComponent = "tJava_6";

				ok_Hash.put("tJava_6", true);
				end_Hash.put("tJava_6", System.currentTimeMillis());

				/**
				 * [tJava_6 end ] stop
				 */
			}// end the resume

			if (resumeEntryMethodName == null || globalResumeTicket) {
				resumeUtil.addLog("CHECKPOINT",
						"CONNECTION:SUBJOB_OK:tJava_6:OnSubjobOk", "", Thread
								.currentThread().getId() + "", "", "", "", "",
						"");
			}

			if (execStat) {
				runStat.updateStatOnConnection("OnSubjobOk5", 0, "ok");
			}

			tJava_7Process(globalMap);

		} catch (java.lang.Exception e) {

			TalendException te = new TalendException(e, currentComponent,
					globalMap);

			throw te;
		} catch (java.lang.Error error) {

			runStat.stopThreadStat();

			throw error;
		} finally {

			try {

				/**
				 * [tJava_6 finally ] start
				 */

				currentComponent = "tJava_6";

				/**
				 * [tJava_6 finally ] stop
				 */
			} catch (java.lang.Exception e) {
				// ignore
			} catch (java.lang.Error error) {
				// ignore
			}
			resourceMap = null;
		}

		globalMap.put("tJava_6_SUBPROCESS_STATE", 1);
	}

	public void tJava_7Process(final java.util.Map<String, Object> globalMap)
			throws TalendException {
		globalMap.put("tJava_7_SUBPROCESS_STATE", 0);

		final boolean execStat = this.execStat;

		String iterateId = "";

		String currentComponent = "";
		java.util.Map<String, Object> resourceMap = new java.util.HashMap<String, Object>();

		try {
			// TDI-39566 avoid throwing an useless Exception
			boolean resumeIt = true;
			if (globalResumeTicket == false && resumeEntryMethodName != null) {
				String currentMethodName = new java.lang.Exception()
						.getStackTrace()[0].getMethodName();
				resumeIt = resumeEntryMethodName.equals(currentMethodName);
			}
			if (resumeIt || globalResumeTicket) { // start the resume
				globalResumeTicket = true;

				/**
				 * [tJava_7 begin ] start
				 */

				ok_Hash.put("tJava_7", false);
				start_Hash.put("tJava_7", System.currentTimeMillis());

				currentComponent = "tJava_7";

				int tos_count_tJava_7 = 0;

				String foo = "bar";
				context.somme = context.identif + 2;
				System.out.println("somm :" + context.somme);

				/**
				 * [tJava_7 begin ] stop
				 */

				/**
				 * [tJava_7 main ] start
				 */

				currentComponent = "tJava_7";

				tos_count_tJava_7++;

				/**
				 * [tJava_7 main ] stop
				 */

				/**
				 * [tJava_7 process_data_begin ] start
				 */

				currentComponent = "tJava_7";

				/**
				 * [tJava_7 process_data_begin ] stop
				 */

				/**
				 * [tJava_7 process_data_end ] start
				 */

				currentComponent = "tJava_7";

				/**
				 * [tJava_7 process_data_end ] stop
				 */

				/**
				 * [tJava_7 end ] start
				 */

				currentComponent = "tJava_7";

				ok_Hash.put("tJava_7", true);
				end_Hash.put("tJava_7", System.currentTimeMillis());

				/**
				 * [tJava_7 end ] stop
				 */
			}// end the resume

		} catch (java.lang.Exception e) {

			TalendException te = new TalendException(e, currentComponent,
					globalMap);

			throw te;
		} catch (java.lang.Error error) {

			runStat.stopThreadStat();

			throw error;
		} finally {

			try {

				/**
				 * [tJava_7 finally ] start
				 */

				currentComponent = "tJava_7";

				/**
				 * [tJava_7 finally ] stop
				 */
			} catch (java.lang.Exception e) {
				// ignore
			} catch (java.lang.Error error) {
				// ignore
			}
			resourceMap = null;
		}

		globalMap.put("tJava_7_SUBPROCESS_STATE", 1);
	}

	public static class row14Struct implements
			routines.system.IPersistableRow<row14Struct> {
		final static byte[] commonByteArrayLock_TECHNIP_test = new byte[0];
		static byte[] commonByteArray_TECHNIP_test = new byte[0];

		public String id;

		public String getId() {
			return this.id;
		}

		private String readString(ObjectInputStream dis) throws IOException {
			String strReturn = null;
			int length = 0;
			length = dis.readInt();
			if (length == -1) {
				strReturn = null;
			} else {
				if (length > commonByteArray_TECHNIP_test.length) {
					if (length < 1024
							&& commonByteArray_TECHNIP_test.length == 0) {
						commonByteArray_TECHNIP_test = new byte[1024];
					} else {
						commonByteArray_TECHNIP_test = new byte[2 * length];
					}
				}
				dis.readFully(commonByteArray_TECHNIP_test, 0, length);
				strReturn = new String(commonByteArray_TECHNIP_test, 0, length,
						utf8Charset);
			}
			return strReturn;
		}

		private void writeString(String str, ObjectOutputStream dos)
				throws IOException {
			if (str == null) {
				dos.writeInt(-1);
			} else {
				byte[] byteArray = str.getBytes(utf8Charset);
				dos.writeInt(byteArray.length);
				dos.write(byteArray);
			}
		}

		public void readData(ObjectInputStream dis) {

			synchronized (commonByteArrayLock_TECHNIP_test) {

				try {

					int length = 0;

					this.id = readString(dis);

				} catch (IOException e) {
					throw new RuntimeException(e);

				}

			}

		}

		public void writeData(ObjectOutputStream dos) {
			try {

				// String

				writeString(this.id, dos);

			} catch (IOException e) {
				throw new RuntimeException(e);
			}

		}

		public String toString() {

			StringBuilder sb = new StringBuilder();
			sb.append(super.toString());
			sb.append("[");
			sb.append("id=" + id);
			sb.append("]");

			return sb.toString();
		}

		/**
		 * Compare keys
		 */
		public int compareTo(row14Struct other) {

			int returnValue = -1;

			return returnValue;
		}

		private int checkNullsAndCompare(Object object1, Object object2) {
			int returnValue = 0;
			if (object1 instanceof Comparable && object2 instanceof Comparable) {
				returnValue = ((Comparable) object1).compareTo(object2);
			} else if (object1 != null && object2 != null) {
				returnValue = compareStrings(object1.toString(),
						object2.toString());
			} else if (object1 == null && object2 != null) {
				returnValue = 1;
			} else if (object1 != null && object2 == null) {
				returnValue = -1;
			} else {
				returnValue = 0;
			}

			return returnValue;
		}

		private int compareStrings(String string1, String string2) {
			return string1.compareTo(string2);
		}

	}

	public void tRowGenerator_1Process(
			final java.util.Map<String, Object> globalMap)
			throws TalendException {
		globalMap.put("tRowGenerator_1_SUBPROCESS_STATE", 0);

		final boolean execStat = this.execStat;

		String iterateId = "";

		String currentComponent = "";
		java.util.Map<String, Object> resourceMap = new java.util.HashMap<String, Object>();

		try {
			// TDI-39566 avoid throwing an useless Exception
			boolean resumeIt = true;
			if (globalResumeTicket == false && resumeEntryMethodName != null) {
				String currentMethodName = new java.lang.Exception()
						.getStackTrace()[0].getMethodName();
				resumeIt = resumeEntryMethodName.equals(currentMethodName);
			}
			if (resumeIt || globalResumeTicket) { // start the resume
				globalResumeTicket = true;

				row14Struct row14 = new row14Struct();

				/**
				 * [tLogRow_5 begin ] start
				 */

				ok_Hash.put("tLogRow_5", false);
				start_Hash.put("tLogRow_5", System.currentTimeMillis());

				currentComponent = "tLogRow_5";

				if (execStat) {
					if (resourceMap.get("inIterateVComp") == null) {

						runStat.updateStatOnConnection("row14" + iterateId, 0,
								0);

					}
				}

				int tos_count_tLogRow_5 = 0;

				// /////////////////////

				final String OUTPUT_FIELD_SEPARATOR_tLogRow_5 = "|";
				java.io.PrintStream consoleOut_tLogRow_5 = null;

				StringBuilder strBuffer_tLogRow_5 = null;
				int nb_line_tLogRow_5 = 0;
				// /////////////////////

				/**
				 * [tLogRow_5 begin ] stop
				 */

				/**
				 * [tRowGenerator_1 begin ] start
				 */

				ok_Hash.put("tRowGenerator_1", false);
				start_Hash.put("tRowGenerator_1", System.currentTimeMillis());

				currentComponent = "tRowGenerator_1";

				int tos_count_tRowGenerator_1 = 0;

				int nb_line_tRowGenerator_1 = 0;
				int nb_max_row_tRowGenerator_1 = 5;

				class tRowGenerator_1Randomizer {
					public String getRandomid() {

						return TalendString.getAsciiRandomString(6);

					}
				}
				tRowGenerator_1Randomizer randtRowGenerator_1 = new tRowGenerator_1Randomizer();

				for (int itRowGenerator_1 = 0; itRowGenerator_1 < nb_max_row_tRowGenerator_1; itRowGenerator_1++) {
					row14.id = randtRowGenerator_1.getRandomid();
					nb_line_tRowGenerator_1++;

					/**
					 * [tRowGenerator_1 begin ] stop
					 */

					/**
					 * [tRowGenerator_1 main ] start
					 */

					currentComponent = "tRowGenerator_1";

					tos_count_tRowGenerator_1++;

					/**
					 * [tRowGenerator_1 main ] stop
					 */

					/**
					 * [tRowGenerator_1 process_data_begin ] start
					 */

					currentComponent = "tRowGenerator_1";

					/**
					 * [tRowGenerator_1 process_data_begin ] stop
					 */

					/**
					 * [tLogRow_5 main ] start
					 */

					currentComponent = "tLogRow_5";

					// row14
					// row14

					if (execStat) {
						runStat.updateStatOnConnection("row14" + iterateId, 1,
								1);
					}

					// /////////////////////

					strBuffer_tLogRow_5 = new StringBuilder();

					if (row14.id != null) { //

						strBuffer_tLogRow_5.append(String.valueOf(row14.id));

					} //

					if (globalMap.get("tLogRow_CONSOLE") != null) {
						consoleOut_tLogRow_5 = (java.io.PrintStream) globalMap
								.get("tLogRow_CONSOLE");
					} else {
						consoleOut_tLogRow_5 = new java.io.PrintStream(
								new java.io.BufferedOutputStream(System.out));
						globalMap.put("tLogRow_CONSOLE", consoleOut_tLogRow_5);
					}
					consoleOut_tLogRow_5
							.println(strBuffer_tLogRow_5.toString());
					consoleOut_tLogRow_5.flush();
					nb_line_tLogRow_5++;
					// ////

					// ////

					// /////////////////////

					tos_count_tLogRow_5++;

					/**
					 * [tLogRow_5 main ] stop
					 */

					/**
					 * [tLogRow_5 process_data_begin ] start
					 */

					currentComponent = "tLogRow_5";

					/**
					 * [tLogRow_5 process_data_begin ] stop
					 */

					/**
					 * [tLogRow_5 process_data_end ] start
					 */

					currentComponent = "tLogRow_5";

					/**
					 * [tLogRow_5 process_data_end ] stop
					 */

					/**
					 * [tRowGenerator_1 process_data_end ] start
					 */

					currentComponent = "tRowGenerator_1";

					/**
					 * [tRowGenerator_1 process_data_end ] stop
					 */

					/**
					 * [tRowGenerator_1 end ] start
					 */

					currentComponent = "tRowGenerator_1";

				}
				globalMap.put("tRowGenerator_1_NB_LINE",
						nb_line_tRowGenerator_1);

				ok_Hash.put("tRowGenerator_1", true);
				end_Hash.put("tRowGenerator_1", System.currentTimeMillis());

				/**
				 * [tRowGenerator_1 end ] stop
				 */

				/**
				 * [tLogRow_5 end ] start
				 */

				currentComponent = "tLogRow_5";

				// ////
				// ////
				globalMap.put("tLogRow_5_NB_LINE", nb_line_tLogRow_5);

				// /////////////////////

				if (execStat) {
					if (resourceMap.get("inIterateVComp") == null
							|| !((Boolean) resourceMap.get("inIterateVComp"))) {
						runStat.updateStatOnConnection("row14" + iterateId, 2,
								0);
					}
				}

				ok_Hash.put("tLogRow_5", true);
				end_Hash.put("tLogRow_5", System.currentTimeMillis());

				/**
				 * [tLogRow_5 end ] stop
				 */

			}// end the resume

			if (resumeEntryMethodName == null || globalResumeTicket) {
				resumeUtil
						.addLog("CHECKPOINT",
								"CONNECTION:SUBJOB_OK:tRowGenerator_1:OnSubjobOk",
								"", Thread.currentThread().getId() + "", "",
								"", "", "", "");
			}

			if (execStat) {
				runStat.updateStatOnConnection("OnSubjobOk4", 0, "ok");
			}

			tFixedFlowInput_3Process(globalMap);

		} catch (java.lang.Exception e) {

			TalendException te = new TalendException(e, currentComponent,
					globalMap);

			throw te;
		} catch (java.lang.Error error) {

			runStat.stopThreadStat();

			throw error;
		} finally {

			try {

				/**
				 * [tRowGenerator_1 finally ] start
				 */

				currentComponent = "tRowGenerator_1";

				/**
				 * [tRowGenerator_1 finally ] stop
				 */

				/**
				 * [tLogRow_5 finally ] start
				 */

				currentComponent = "tLogRow_5";

				/**
				 * [tLogRow_5 finally ] stop
				 */

			} catch (java.lang.Exception e) {
				// ignore
			} catch (java.lang.Error error) {
				// ignore
			}
			resourceMap = null;
		}

		globalMap.put("tRowGenerator_1_SUBPROCESS_STATE", 1);
	}

	public String resuming_logs_dir_path = null;
	public String resuming_checkpoint_path = null;
	public String parent_part_launcher = null;
	private String resumeEntryMethodName = null;
	private boolean globalResumeTicket = false;

	public boolean watch = false;
	// portStats is null, it means don't execute the statistics
	public Integer portStats = null;
	public int portTraces = 4334;
	public String clientHost;
	public String defaultClientHost = "localhost";
	public String contextStr = "Default";
	public boolean isDefaultContext = true;
	public String pid = "0";
	public String rootPid = null;
	public String fatherPid = null;
	public String fatherNode = null;
	public long startTime = 0;
	public boolean isChildJob = false;
	public String log4jLevel = "";

	private boolean execStat = true;

	private ThreadLocal<java.util.Map<String, String>> threadLocal = new ThreadLocal<java.util.Map<String, String>>() {
		protected java.util.Map<String, String> initialValue() {
			java.util.Map<String, String> threadRunResultMap = new java.util.HashMap<String, String>();
			threadRunResultMap.put("errorCode", null);
			threadRunResultMap.put("status", "");
			return threadRunResultMap;
		};
	};

	private PropertiesWithType context_param = new PropertiesWithType();
	public java.util.Map<String, Object> parentContextMap = new java.util.HashMap<String, Object>();

	public String status = "";

	public static void main(String[] args) {
		final test testClass = new test();

		int exitCode = testClass.runJobInTOS(args);

		System.exit(exitCode);
	}

	public String[][] runJob(String[] args) {

		int exitCode = runJobInTOS(args);
		String[][] bufferValue = new String[][] { { Integer.toString(exitCode) } };

		return bufferValue;
	}

	public boolean hastBufferOutputComponent() {
		boolean hastBufferOutput = false;

		return hastBufferOutput;
	}

	public int runJobInTOS(String[] args) {
		// reset status
		status = "";

		String lastStr = "";
		for (String arg : args) {
			if (arg.equalsIgnoreCase("--context_param")) {
				lastStr = arg;
			} else if (lastStr.equals("")) {
				evalParam(arg);
			} else {
				evalParam(lastStr + " " + arg);
				lastStr = "";
			}
		}

		if (clientHost == null) {
			clientHost = defaultClientHost;
		}

		if (pid == null || "0".equals(pid)) {
			pid = TalendString.getAsciiRandomString(6);
		}

		if (rootPid == null) {
			rootPid = pid;
		}
		if (fatherPid == null) {
			fatherPid = pid;
		} else {
			isChildJob = true;
		}

		if (portStats != null) {
			// portStats = -1; //for testing
			if (portStats < 0 || portStats > 65535) {
				// issue:10869, the portStats is invalid, so this client socket
				// can't open
				System.err.println("The statistics socket port " + portStats
						+ " is invalid.");
				execStat = false;
			}
		} else {
			execStat = false;
		}

		try {
			// call job/subjob with an existing context, like:
			// --context=production. if without this parameter, there will use
			// the default context instead.
			java.io.InputStream inContext = test.class.getClassLoader()
					.getResourceAsStream(
							"technip/test_0_1/contexts/" + contextStr
									+ ".properties");
			if (inContext == null) {
				inContext = test.class.getClassLoader().getResourceAsStream(
						"config/contexts/" + contextStr + ".properties");
			}
			if (inContext != null) {
				// defaultProps is in order to keep the original context value
				defaultProps.load(inContext);
				inContext.close();
				context = new ContextProperties(defaultProps);
			} else if (!isDefaultContext) {
				// print info and job continue to run, for case: context_param
				// is not empty.
				System.err.println("Could not find the context " + contextStr);
			}

			if (!context_param.isEmpty()) {
				context.putAll(context_param);
				// set types for params from parentJobs
				for (Object key : context_param.keySet()) {
					String context_key = key.toString();
					String context_type = context_param
							.getContextType(context_key);
					context.setContextType(context_key, context_type);

				}
			}
			context.setContextType("ID", "id_String");

			context.ID = (String) context.getProperty("ID");
			context.setContextType("FULL_Endpt", "id_String");

			context.FULL_Endpt = (String) context.getProperty("FULL_Endpt");
			context.setContextType("FULL_PassW", "id_Password");

			String pwd_FULL_PassW_value = context.getProperty("FULL_PassW");
			context.FULL_PassW = null;
			if (pwd_FULL_PassW_value != null) {
				if (context_param.containsKey("FULL_PassW")) {// no need to
																// decrypt if it
																// come from
																// program
																// argument or
																// parent job
																// runtime
					context.FULL_PassW = pwd_FULL_PassW_value;
				} else if (!pwd_FULL_PassW_value.isEmpty()) {
					try {
						context.FULL_PassW = routines.system.PasswordEncryptUtil
								.decryptPassword(pwd_FULL_PassW_value);
						context.put("FULL_PassW", context.FULL_PassW);
					} catch (java.lang.RuntimeException e) {
						// do nothing
					}
				}
			}
			context.setContextType("FULL_SecuK", "id_Password");

			String pwd_FULL_SecuK_value = context.getProperty("FULL_SecuK");
			context.FULL_SecuK = null;
			if (pwd_FULL_SecuK_value != null) {
				if (context_param.containsKey("FULL_SecuK")) {// no need to
																// decrypt if it
																// come from
																// program
																// argument or
																// parent job
																// runtime
					context.FULL_SecuK = pwd_FULL_SecuK_value;
				} else if (!pwd_FULL_SecuK_value.isEmpty()) {
					try {
						context.FULL_SecuK = routines.system.PasswordEncryptUtil
								.decryptPassword(pwd_FULL_SecuK_value);
						context.put("FULL_SecuK", context.FULL_SecuK);
					} catch (java.lang.RuntimeException e) {
						// do nothing
					}
				}
			}
			context.setContextType("FULL_UserId", "id_String");

			context.FULL_UserId = (String) context.getProperty("FULL_UserId");
			context.setContextType("CIBLE_Endpt", "id_String");

			context.CIBLE_Endpt = (String) context.getProperty("CIBLE_Endpt");
			context.setContextType("CIBLE_PassW", "id_Password");

			String pwd_CIBLE_PassW_value = context.getProperty("CIBLE_PassW");
			context.CIBLE_PassW = null;
			if (pwd_CIBLE_PassW_value != null) {
				if (context_param.containsKey("CIBLE_PassW")) {// no need to
																// decrypt if it
																// come from
																// program
																// argument or
																// parent job
																// runtime
					context.CIBLE_PassW = pwd_CIBLE_PassW_value;
				} else if (!pwd_CIBLE_PassW_value.isEmpty()) {
					try {
						context.CIBLE_PassW = routines.system.PasswordEncryptUtil
								.decryptPassword(pwd_CIBLE_PassW_value);
						context.put("CIBLE_PassW", context.CIBLE_PassW);
					} catch (java.lang.RuntimeException e) {
						// do nothing
					}
				}
			}
			context.setContextType("CIBLE_SecuK", "id_Password");

			String pwd_CIBLE_SecuK_value = context.getProperty("CIBLE_SecuK");
			context.CIBLE_SecuK = null;
			if (pwd_CIBLE_SecuK_value != null) {
				if (context_param.containsKey("CIBLE_SecuK")) {// no need to
																// decrypt if it
																// come from
																// program
																// argument or
																// parent job
																// runtime
					context.CIBLE_SecuK = pwd_CIBLE_SecuK_value;
				} else if (!pwd_CIBLE_SecuK_value.isEmpty()) {
					try {
						context.CIBLE_SecuK = routines.system.PasswordEncryptUtil
								.decryptPassword(pwd_CIBLE_SecuK_value);
						context.put("CIBLE_SecuK", context.CIBLE_SecuK);
					} catch (java.lang.RuntimeException e) {
						// do nothing
					}
				}
			}
			context.setContextType("CIBLE_UserId", "id_String");

			context.CIBLE_UserId = (String) context.getProperty("CIBLE_UserId");
			context.setContextType("SOURCE_Endpt", "id_String");

			context.SOURCE_Endpt = (String) context.getProperty("SOURCE_Endpt");
			context.setContextType("SOURCE_PassW", "id_Password");

			String pwd_SOURCE_PassW_value = context.getProperty("SOURCE_PassW");
			context.SOURCE_PassW = null;
			if (pwd_SOURCE_PassW_value != null) {
				if (context_param.containsKey("SOURCE_PassW")) {// no need to
																// decrypt if it
																// come from
																// program
																// argument or
																// parent job
																// runtime
					context.SOURCE_PassW = pwd_SOURCE_PassW_value;
				} else if (!pwd_SOURCE_PassW_value.isEmpty()) {
					try {
						context.SOURCE_PassW = routines.system.PasswordEncryptUtil
								.decryptPassword(pwd_SOURCE_PassW_value);
						context.put("SOURCE_PassW", context.SOURCE_PassW);
					} catch (java.lang.RuntimeException e) {
						// do nothing
					}
				}
			}
			context.setContextType("SOURCE_SecuK", "id_Password");

			String pwd_SOURCE_SecuK_value = context.getProperty("SOURCE_SecuK");
			context.SOURCE_SecuK = null;
			if (pwd_SOURCE_SecuK_value != null) {
				if (context_param.containsKey("SOURCE_SecuK")) {// no need to
																// decrypt if it
																// come from
																// program
																// argument or
																// parent job
																// runtime
					context.SOURCE_SecuK = pwd_SOURCE_SecuK_value;
				} else if (!pwd_SOURCE_SecuK_value.isEmpty()) {
					try {
						context.SOURCE_SecuK = routines.system.PasswordEncryptUtil
								.decryptPassword(pwd_SOURCE_SecuK_value);
						context.put("SOURCE_SecuK", context.SOURCE_SecuK);
					} catch (java.lang.RuntimeException e) {
						// do nothing
					}
				}
			}
			context.setContextType("SOURCE_UserId", "id_String");

			context.SOURCE_UserId = (String) context
					.getProperty("SOURCE_UserId");
			context.setContextType("offset", "id_Integer");

			try {
				context.offset = routines.system.ParserUtils
						.parseTo_Integer(context.getProperty("offset"));
			} catch (NumberFormatException e) {
				System.err.println(String.format(
						"Null value will be used for context parameter %s: %s",
						"offset", e.getMessage()));
				context.offset = null;
			}
			context.setContextType("idcont", "id_String");

			context.idcont = (String) context.getProperty("idcont");
			context.setContextType("identif", "id_Integer");

			try {
				context.identif = routines.system.ParserUtils
						.parseTo_Integer(context.getProperty("identif"));
			} catch (NumberFormatException e) {
				System.err.println(String.format(
						"Null value will be used for context parameter %s: %s",
						"identif", e.getMessage()));
				context.identif = null;
			}
			context.setContextType("somme", "id_Integer");

			try {
				context.somme = routines.system.ParserUtils
						.parseTo_Integer(context.getProperty("somme"));
			} catch (NumberFormatException e) {
				System.err.println(String.format(
						"Null value will be used for context parameter %s: %s",
						"somme", e.getMessage()));
				context.somme = null;
			}
		} catch (java.io.IOException ie) {
			System.err.println("Could not load context " + contextStr);
			ie.printStackTrace();
		}

		// get context value from parent directly
		if (parentContextMap != null && !parentContextMap.isEmpty()) {
			if (parentContextMap.containsKey("ID")) {
				context.ID = (String) parentContextMap.get("ID");
			}
			if (parentContextMap.containsKey("FULL_Endpt")) {
				context.FULL_Endpt = (String) parentContextMap
						.get("FULL_Endpt");
			}
			if (parentContextMap.containsKey("FULL_PassW")) {
				context.FULL_PassW = (java.lang.String) parentContextMap
						.get("FULL_PassW");
			}
			if (parentContextMap.containsKey("FULL_SecuK")) {
				context.FULL_SecuK = (java.lang.String) parentContextMap
						.get("FULL_SecuK");
			}
			if (parentContextMap.containsKey("FULL_UserId")) {
				context.FULL_UserId = (String) parentContextMap
						.get("FULL_UserId");
			}
			if (parentContextMap.containsKey("CIBLE_Endpt")) {
				context.CIBLE_Endpt = (String) parentContextMap
						.get("CIBLE_Endpt");
			}
			if (parentContextMap.containsKey("CIBLE_PassW")) {
				context.CIBLE_PassW = (java.lang.String) parentContextMap
						.get("CIBLE_PassW");
			}
			if (parentContextMap.containsKey("CIBLE_SecuK")) {
				context.CIBLE_SecuK = (java.lang.String) parentContextMap
						.get("CIBLE_SecuK");
			}
			if (parentContextMap.containsKey("CIBLE_UserId")) {
				context.CIBLE_UserId = (String) parentContextMap
						.get("CIBLE_UserId");
			}
			if (parentContextMap.containsKey("SOURCE_Endpt")) {
				context.SOURCE_Endpt = (String) parentContextMap
						.get("SOURCE_Endpt");
			}
			if (parentContextMap.containsKey("SOURCE_PassW")) {
				context.SOURCE_PassW = (java.lang.String) parentContextMap
						.get("SOURCE_PassW");
			}
			if (parentContextMap.containsKey("SOURCE_SecuK")) {
				context.SOURCE_SecuK = (java.lang.String) parentContextMap
						.get("SOURCE_SecuK");
			}
			if (parentContextMap.containsKey("SOURCE_UserId")) {
				context.SOURCE_UserId = (String) parentContextMap
						.get("SOURCE_UserId");
			}
			if (parentContextMap.containsKey("offset")) {
				context.offset = (Integer) parentContextMap.get("offset");
			}
			if (parentContextMap.containsKey("idcont")) {
				context.idcont = (String) parentContextMap.get("idcont");
			}
			if (parentContextMap.containsKey("identif")) {
				context.identif = (Integer) parentContextMap.get("identif");
			}
			if (parentContextMap.containsKey("somme")) {
				context.somme = (Integer) parentContextMap.get("somme");
			}
		}

		// Resume: init the resumeUtil
		resumeEntryMethodName = ResumeUtil
				.getResumeEntryMethodName(resuming_checkpoint_path);
		resumeUtil = new ResumeUtil(resuming_logs_dir_path, isChildJob, rootPid);
		resumeUtil.initCommonInfo(pid, rootPid, fatherPid, projectName,
				jobName, contextStr, jobVersion);

		List<String> parametersToEncrypt = new java.util.ArrayList<String>();
		parametersToEncrypt.add("FULL_PassW");
		parametersToEncrypt.add("FULL_SecuK");
		parametersToEncrypt.add("CIBLE_PassW");
		parametersToEncrypt.add("CIBLE_SecuK");
		parametersToEncrypt.add("SOURCE_PassW");
		parametersToEncrypt.add("SOURCE_SecuK");
		// Resume: jobStart
		resumeUtil.addLog("JOB_STARTED", "JOB:" + jobName,
				parent_part_launcher, Thread.currentThread().getId() + "", "",
				"", "", "",
				resumeUtil.convertToJsonText(context, parametersToEncrypt));

		if (execStat) {
			try {
				runStat.openSocket(!isChildJob);
				runStat.setAllPID(rootPid, fatherPid, pid, jobName);
				runStat.startThreadStat(clientHost, portStats);
				runStat.updateStatOnJob(RunStat.JOBSTART, fatherNode);
			} catch (java.io.IOException ioException) {
				ioException.printStackTrace();
			}
		}

		java.util.concurrent.ConcurrentHashMap<Object, Object> concurrentHashMap = new java.util.concurrent.ConcurrentHashMap<Object, Object>();
		globalMap.put("concurrentHashMap", concurrentHashMap);

		long startUsedMemory = Runtime.getRuntime().totalMemory()
				- Runtime.getRuntime().freeMemory();
		long endUsedMemory = 0;
		long end = 0;

		startTime = System.currentTimeMillis();

		try {
			errorCode = null;
			Implicit_Context_RegexProcess(globalMap);
			if (!"failure".equals(status)) {
				status = "end";
			}
		} catch (TalendException e_Implicit_Context_Regex) {
			globalMap.put("Implicit_Context_Regex_SUBPROCESS_STATE", -1);

			e_Implicit_Context_Regex.printStackTrace();

		}

		this.globalResumeTicket = true;// to run tPreJob

		this.globalResumeTicket = false;// to run others jobs

		try {
			errorCode = null;
			tRowGenerator_1Process(globalMap);
			if (!"failure".equals(status)) {
				status = "end";
			}
		} catch (TalendException e_tRowGenerator_1) {
			globalMap.put("tRowGenerator_1_SUBPROCESS_STATE", -1);

			e_tRowGenerator_1.printStackTrace();

		}

		this.globalResumeTicket = true;// to run tPostJob

		end = System.currentTimeMillis();

		if (watch) {
			System.out.println((end - startTime) + " milliseconds");
		}

		endUsedMemory = Runtime.getRuntime().totalMemory()
				- Runtime.getRuntime().freeMemory();
		if (false) {
			System.out.println((endUsedMemory - startUsedMemory)
					+ " bytes memory increase when running : test");
		}

		if (execStat) {
			runStat.updateStatOnJob(RunStat.JOBEND, fatherNode);
			runStat.stopThreadStat();
		}
		int returnCode = 0;
		if (errorCode == null) {
			returnCode = status != null && status.equals("failure") ? 1 : 0;
		} else {
			returnCode = errorCode.intValue();
		}
		resumeUtil.addLog("JOB_ENDED", "JOB:" + jobName, parent_part_launcher,
				Thread.currentThread().getId() + "", "", "" + returnCode, "",
				"", "");

		return returnCode;

	}

	// only for OSGi env
	public void destroy() {

	}

	private java.util.Map<String, Object> getSharedConnections4REST() {
		java.util.Map<String, Object> connections = new java.util.HashMap<String, Object>();

		return connections;
	}

	private void evalParam(String arg) {
		if (arg.startsWith("--resuming_logs_dir_path")) {
			resuming_logs_dir_path = arg.substring(25);
		} else if (arg.startsWith("--resuming_checkpoint_path")) {
			resuming_checkpoint_path = arg.substring(27);
		} else if (arg.startsWith("--parent_part_launcher")) {
			parent_part_launcher = arg.substring(23);
		} else if (arg.startsWith("--watch")) {
			watch = true;
		} else if (arg.startsWith("--stat_port=")) {
			String portStatsStr = arg.substring(12);
			if (portStatsStr != null && !portStatsStr.equals("null")) {
				portStats = Integer.parseInt(portStatsStr);
			}
		} else if (arg.startsWith("--trace_port=")) {
			portTraces = Integer.parseInt(arg.substring(13));
		} else if (arg.startsWith("--client_host=")) {
			clientHost = arg.substring(14);
		} else if (arg.startsWith("--context=")) {
			contextStr = arg.substring(10);
			isDefaultContext = false;
		} else if (arg.startsWith("--father_pid=")) {
			fatherPid = arg.substring(13);
		} else if (arg.startsWith("--root_pid=")) {
			rootPid = arg.substring(11);
		} else if (arg.startsWith("--father_node=")) {
			fatherNode = arg.substring(14);
		} else if (arg.startsWith("--pid=")) {
			pid = arg.substring(6);
		} else if (arg.startsWith("--context_type")) {
			String keyValue = arg.substring(15);
			int index = -1;
			if (keyValue != null && (index = keyValue.indexOf('=')) > -1) {
				if (fatherPid == null) {
					context_param.setContextType(keyValue.substring(0, index),
							replaceEscapeChars(keyValue.substring(index + 1)));
				} else { // the subjob won't escape the especial chars
					context_param.setContextType(keyValue.substring(0, index),
							keyValue.substring(index + 1));
				}

			}

		} else if (arg.startsWith("--context_param")) {
			String keyValue = arg.substring(16);
			int index = -1;
			if (keyValue != null && (index = keyValue.indexOf('=')) > -1) {
				if (fatherPid == null) {
					context_param.put(keyValue.substring(0, index),
							replaceEscapeChars(keyValue.substring(index + 1)));
				} else { // the subjob won't escape the especial chars
					context_param.put(keyValue.substring(0, index),
							keyValue.substring(index + 1));
				}
			}
		} else if (arg.startsWith("--log4jLevel=")) {
			log4jLevel = arg.substring(13);
		}

	}

	private static final String NULL_VALUE_EXPRESSION_IN_COMMAND_STRING_FOR_CHILD_JOB_ONLY = "<TALEND_NULL>";

	private final String[][] escapeChars = { { "\\\\", "\\" }, { "\\n", "\n" },
			{ "\\'", "\'" }, { "\\r", "\r" }, { "\\f", "\f" }, { "\\b", "\b" },
			{ "\\t", "\t" } };

	private String replaceEscapeChars(String keyValue) {

		if (keyValue == null || ("").equals(keyValue.trim())) {
			return keyValue;
		}

		StringBuilder result = new StringBuilder();
		int currIndex = 0;
		while (currIndex < keyValue.length()) {
			int index = -1;
			// judege if the left string includes escape chars
			for (String[] strArray : escapeChars) {
				index = keyValue.indexOf(strArray[0], currIndex);
				if (index >= 0) {

					result.append(keyValue.substring(currIndex,
							index + strArray[0].length()).replace(strArray[0],
							strArray[1]));
					currIndex = index + strArray[0].length();
					break;
				}
			}
			// if the left string doesn't include escape chars, append the left
			// into the result
			if (index < 0) {
				result.append(keyValue.substring(currIndex));
				currIndex = currIndex + keyValue.length();
			}
		}

		return result.toString();
	}

	public Integer getErrorCode() {
		return errorCode;
	}

	public String getStatus() {
		return status;
	}

	ResumeUtil resumeUtil = null;
}
/************************************************************************************************
 * 89916 characters generated by Talend Open Studio for Data Integration on the
 * 27 janvier 2020 11:55:20 CET
 ************************************************************************************************/
